### ISSUE TITLE
These do not work.

### ISSUE THREAD

**Issue by bachmeyer** [PacktPublishing/Hands-On-Cryptography-with-Python#1]
These do not work with python 3.  I have the book and the supplements and have not been able to run any without significant modification.  I was able to find your git by searching to see why the caesar1 was not properly working.  I am guessing there are significant changes to python 3 that cause none of the supplements to properly work.

**Comment by gaurav-packt** [comment]
Thanks for the update.

**Comment by mloskot** [comment]
The chapter [Installing and setting up Python](https://subscription.packtpub.com/book/networking_and_servers/9781789534443/1/ch01lvl1sec10/installing-and-setting-up-python)  is clear about the Python version requirement:

>  In this book, we will use Python 2.7.12.
